project:
  type: website
  output-dir: docs


website:
  title: "Your Name"
  navbar:
    logo: imgs/lab_sit_logo.png
    background: primary
    foreground: light
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
  page-footer:
    center: "© 2025 Your Name · Built with [Quarto](https://quarto.org)"
    background: light


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: right
    smooth-scroll: true
